DIMESHIFT_NAME = "dimeshift"
PAGEKIT_NAME = "pagekit"
PETCLINIC_NAME = "petclinic"
PHOENIX_NAME = "phoenix"
RETROBOARD_NAME = "retroboard"
SPLITTYPIE_NAME = "splittypie"

RANDOM_GENERATOR_NAME = "random"
DISTANCE_GENERATOR_NAME = "distance"
QGRAMS_GENERATOR_NAME = "qgrams"
LENGTH_GENERATOR_NAME = "length"
SIMIDF_GENERATOR_NAME = "simidf"
TFIDF_GENERATOR_NAME = "tfidf"
JSART_GENERATOR_NAME = "jsart"
JSLE_A_GENERATOR_NAME = "jsle_a"
JSLE_B_GENERATOR_NAME = "jsle_b"
JSLE_C_GENERATOR_NAME = "jsle_c"

INPUT_DIVERSITY_STRATEGY_NAME = "input"
SEQUENCE_DIVERSITY_STRATEGY_NAME = "sequence"

APP_NAMES = [
    DIMESHIFT_NAME,
    PAGEKIT_NAME,
    PETCLINIC_NAME,
    PHOENIX_NAME,
    RETROBOARD_NAME,
    SPLITTYPIE_NAME,
]
GENERATOR_NAMES = [
    RANDOM_GENERATOR_NAME,
    DISTANCE_GENERATOR_NAME,
    QGRAMS_GENERATOR_NAME,
    LENGTH_GENERATOR_NAME,
    SIMIDF_GENERATOR_NAME,
    TFIDF_GENERATOR_NAME,
    JSART_GENERATOR_NAME,
    JSLE_A_GENERATOR_NAME,
    JSLE_B_GENERATOR_NAME,
    JSLE_C_GENERATOR_NAME,
]
DIVERSITY_STRATEGY_NAMES = [
    INPUT_DIVERSITY_STRATEGY_NAME,
    SEQUENCE_DIVERSITY_STRATEGY_NAME,
]
CHROME_CONTAINER_NAME = "chrome"
RUNTIME_CONTAINER_NAME = "runtime"
